# export LD_LIBRARY_PATH="/usr/local/gdev/lib64:$LD_LIBRARY_PATH"
# export PATH="/usr/local/gdev/bin:$PATH"
export PATH="/usr/local/cuda/bin:$PATH"
export PATH="/usr/local/cuda-8.0/bin:$PATH"
# export LD_LIBRARY_PATH="/usr/local/cuda-7.0/lib64:$LD_LIBRARY_PATH"
